import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c1b",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffdad8",
        "on-surface-variant": "#5b403f",
        "surface-container-low": "#f4f4f2",
        "on-secondary-fixed": "#2d1600",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#6b3b00",
        "on-tertiary-fixed": "#1c1b1b",
        primary: "#98001b",
        "on-primary-fixed-variant": "#930019",
        "inverse-surface": "#2f3130",
        "inverse-primary": "#ffb3b0",
        tertiary: "#4a4949",
        "surface-variant": "#e2e3e1",
        "on-primary-fixed": "#410006",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb3b0",
        "primary-container": "#be1e2d",
        "surface-container": "#eeeeec",
        "secondary-fixed-dim": "#ffb874",
        "on-surface": "#1a1c1b",
        "surface-container-highest": "#e2e3e1",
        surface: "#f9f9f7",
        "on-primary-container": "#ffd3d1",
        "inverse-on-surface": "#f1f1ef",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-tint": "#b91a2a",
        "secondary-fixed": "#ffdcbf",
        outline: "#8f6f6e",
        "surface-container-high": "#e8e8e6",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary-container": "#663800",
        "tertiary-container": "#626161",
        secondary: "#8c4f00",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed-variant": "#474746",
        "on-error": "#ffffff",
        "outline-variant": "#e3bebb",
        "surface-dim": "#dadad8",
        "surface-bright": "#f9f9f7",
        "secondary-container": "#fd9923",
        "on-tertiary-container": "#dfdddc",
        "on-secondary": "#ffffff",
        background: "#f9f9f7",
        // Warna tombol ORDER (club.hifeed.co)
        club: "#be1e2d",
        "club-hover": "#98001b",
        "on-club": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        gutter: "24px",
        "max-width": "1280px",
        "margin-desktop": "64px",
        base: "8px",
      },
      fontFamily: {
        "headline-lg": ["var(--font-hanken-grotesk)", "sans-serif"],
        "body-lg": ["var(--font-manrope)", "sans-serif"],
        "body-md": ["var(--font-manrope)", "sans-serif"],
        "label-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "headline-lg-mobile": ["var(--font-hanken-grotesk)", "sans-serif"],
        "display-xl": ["var(--font-hanken-grotesk)", "sans-serif"],
        "title-md": ["var(--font-hanken-grotesk)", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "700" },
        ],
        "display-xl": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      maxWidth: {
        "max-width": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
